export const WS_CONNECTION_START_ALL = 'WS_CONNECTION_START_ALL';
export const WS_CONNECTION_START_PRIVET = 'WS_CONNECTION_START_PRIVET';
export const WS_CONNECTION_START_PRIVATE_ORDER = 'WS_CONNECTION_START_PRIVATE_ORDER' 
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_CLOSE = 'WS_CLOSE';
export const WS_GET_ITEMS_MESSAGE = 'WS_GET_ITEMS_MESSAGE';

export const selectOrders = state => state.wsSocketOrders
