export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";
export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_INCREMENT_CART = "GET_INCREMENT_CART";
export const GET_DECREMENT_CATR = "GET_DECREMENT_CATR";
export const APPLY_ORDER_DETAILS_SUCCESS = "APPLY_ORDER_DETAILS_SUCCESS";
export const APPLY_ORDER_DETAILS_REQUEST = "APPLY_ORDER_DETAILS_REQUEST";
export const APPLY_ORDER_DETAILS_FAILED = "APPLY_ORDER_DETAILS_FAILED";
export const GET_CURRENT_TAB = "GET_CURRENT_TAB";
export const GET_DROP_ITEM = "GET_DROP_ITEM";
export const GET_DROP_BUN = "GET_DROP_BUN";
export const GET_DRAG_DROP_LI = "GET_DRAG_DROP_LI";
export const GET_CURRENT_CLICK_TAB = "GET_CURRENT_CLICK_TAB";
export const GET_CURENT_LOCAL_STATE = "GET_CURENT_LOCAL_STATE";

export const APPLY_PASS_REQUEST = 'APPLY_PASS_REQUEST';
export const APPLY_PASS_FAILED = 'APPLY_PASS_FAILED';
export const APPLY_PASS_SUCCES = 'APPLY_PASS_SUCCES';

export const APPLY_PERSON_REQUEST = 'APPLY_NEW_PERSON_REQUEST';
export const APPLY_PERSON_FAILED = 'APPLY_NEW_PERSON_FAILED';
export const APPLY_PERSON_SUCCESS = 'APPLY_NEW_PERSON_SUCCESS';
export const MAKE_PERSON_TOKE = 'MAKE_PERSON_TOKE';
export const APPLY_PERSON_EXIT_REQUEST = 'APPLY_PERSON_EXIT_REQUEST';
export const APPLY_PERSON_EXIT_FAILED = 'APPLY_PERSON_EXIT_FAILED';
export const APPLY_PERSON_EXIT_SUCCESS = 'APPLY_PERSON_EXIT_SUCCESS';
export const CLEAN_SUCCES_CONSTRUCTOR = 'CLEAN_SUCCES_CONSTRUCTOR';

export const WS_CONNECTION_START_ALL = 'WS_CONNECTION_START_ALL';
export const WS_CONNECTION_START_PRIVATE = 'WS_CONNECTION_START_PRIVATE';
export const WS_CONNECTION_START_PRIVATE_ORDER = 'WS_CONNECTION_START_PRIVATE_ORDER'; 
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_CLOSE = 'WS_CLOSE';
export const WS_GET_ITEMS_MESSAGE = 'WS_GET_ITEMS_MESSAGE';


